export const portfolioProjects = [
  {
    id: 1,
    title: 'Restoring Control After a Market Shock',
    category: 'Strategy Consulting',
    description: 'A modular transformer manufacturing company operating in the energy systems sector had built a strong position in the Lithuanian market over many years. Its production infrastructure, processes, and commercial focus were optimized for a stable domestic demand environment.',
    result: '€4 million to €9 million revenue increase',
    tags: ['Strategy Consulting', 'Market Entry', 'B2B'],
    image: '/wooden-products-factory.jpg',
    challenge: 'A modular transformer manufacturing company operating in the energy systems sector had built a strong position in the Lithuanian market over many years. Its production infrastructure, processes, and commercial focus were optimized for a stable domestic demand environment. That environment changed abruptly. A sudden 70% reduction in public investment into energy system upgrades triggered a sector-wide shock. Local demand collapsed, contracts disappeared, and revenue visibility deteriorated within months. The company absorbed a €600,000 loss, placing operational continuity under pressure. The challenge was not technical capability or product quality. The challenge was structural. Production assets were highly specialized, commercial activity was concentrated in one market, and decision-making had been shaped by a single demand source. When that source disappeared, the entire system was exposed.',
    solution: 'The role of Rotomskis Joint Ventures focused on restoring control through integration rather than short-term fixes. Work began with strategic sessions to redefine the company’s market logic — identifying export niches where existing production capabilities could remain competitive without requiring major capital reinvestment. This reframed expansion not as diversification, but as selective market repositioning. In parallel, a dedicated export sales structure was formed to operate outside the domestic market. Commercial leadership, partner outreach, and sales execution were aligned around a single expansion sequence, prioritizing trust-building and long-term customer relationships over rapid volume growth. As integration replaced fragmentation, execution regained coherence.',
    timeline: '24 months',
    metrics: [
        { label: 'Revenue Growth', value: '€4 million to €9 million', highlight: true },
       { label: 'Countries', value: '2 Nations', highlight: false },
      { label: 'Net Profit', value: '€450,000 ', highlight: true },
    ],
    outcomes: [
      'revenue increased from €4 million to €9 million',
      'restoring operational stability and reversing the prior losses.',
      'The company returned to profitability with €450,000 in net profit',
        'established a diversified export presence across Scandinavian and German markets',
        'reduced dependency on domestic public investment cycles.'
      
    ],
  },
  {
    id: 2,
    title: 'Tech Startup Global Launch',
    category: 'market',
    description: 'Navigated market entry strategy for Lithuanian software company targeting US and Asian markets',
    result: '15M valuation increase',
    tags: ['SaaS', 'Market Entry', 'Growth'],
    image: '/technology-startup-office.jpg',
    challenge: 'A promising SaaS startup with strong product-market fit in Europe struggled to navigate US and Asian markets. Regulatory differences, cultural nuances, and capital requirements posed significant barriers.',
    solution: 'Created targeted market entry strategies for each region, secured partnerships with local investors, navigated regulatory requirements, and built go-to-market strategies customized for each market.',
    timeline: '12 months',
    metrics: [
      { label: 'Valuation Increase', value: '15M', highlight: true },
      { label: 'New Markets', value: '3 Regions', highlight: false },
      { label: 'Customer Growth', value: '250%', highlight: false },
      { label: 'Funding Raised', value: '8.5M', highlight: false },
    ],
    outcomes: [
      'Successfully entered US market with 200+ enterprise customers',
      'Established operations in Singapore for Asian market expansion',
      'Raised Series A funding at 15M valuation',
      'Achieved 250% customer growth year-over-year',
    ],
  },
  {
    id: 3,
    title: 'Manufacturing Sector Transformation',
    category: 'tech',
    description: 'Modernized export processes and integrated digital solutions for traditional manufacturer',
    result: '50% cost reduction',
    tags: ['Operations', 'Digitization', 'Efficiency'],
    image: '/manufacturing-facility-production.jpg',
    challenge: 'Legacy manufacturing operations with manual processes, inefficient supply chains, and high operational costs. Limited export capability despite quality products.',
    solution: 'Implemented ERP systems, digitized supply chain management, optimized production scheduling, and integrated logistics platforms for seamless international shipping.',
    timeline: '14 months',
    metrics: [
      { label: 'Cost Reduction', value: '50%', highlight: true },
      { label: 'Production Speed', value: '35% Faster', highlight: false },
      { label: 'Quality Improvement', value: '98% Standard', highlight: false },
      { label: 'Export Capacity', value: '3x', highlight: false },
    ],
    outcomes: [
      'Reduced operational costs by 50% through automation',
      'Increased production capacity by 200%',
      'Achieved ISO certifications across all operations',
      'Enabled exports to 12 international markets',
    ],
  },
  {
    id: 4,
    title: 'Food & Beverage International Brand',
    category: 'export',
    description: 'Created distribution network across 8 European countries for premium Lithuanian spirits',
    result: '250% market growth',
    tags: ['Food & Beverage', 'Distribution', 'Branding'],
    image: '/premium-beverage-products.jpg',
    challenge: 'Premium Lithuanian spirit brand with strong domestic presence but limited international recognition. Needed to navigate strict EU regulations and establish premium market positioning.',
    solution: 'Built comprehensive distribution networks in 8 countries, created localized marketing strategies, secured premium retail partnerships, and managed regulatory compliance across markets.',
    timeline: '16 months',
    metrics: [
      { label: 'Market Growth', value: '250%', highlight: true },
      { label: 'Countries', value: '8 Nations', highlight: false },
      { label: 'Retail Partners', value: '150+', highlight: false },
      { label: 'Sales Volume', value: '2.5M Bottles', highlight: false },
    ],
    outcomes: [
      'Established presence in 8 European premium markets',
      'Built partnerships with 150+ premium retailers',
      'Increased sales volume from 400K to 2.5M bottles annually',
      'Created premium brand positioning in competitive markets',
    ],
  },
  {
    id: 5,
    title: 'Enterprise B2B Partnership Model',
    category: 'market',
    description: 'Established strategic partnerships and supply chain for major industrial component manufacturer',
    result: '€2.5M annual contracts',
    tags: ['B2B', 'Partnerships', 'Supply Chain'],
    image: '/industrial-machinery.png',
    challenge: 'Industrial manufacturer struggled with fragmented buyer relationships and lacked structured approach to enterprise B2B sales. Limited partnership infrastructure for scaling.',
    solution: 'Developed comprehensive B2B partnership framework, created structured procurement processes, built sales infrastructure for enterprise clients, and established long-term contract management systems.',
    timeline: '13 months',
    metrics: [
      { label: 'Annual Contracts', value: '€2.5M', highlight: true },
      { label: 'Enterprise Clients', value: '18 Companies', highlight: false },
      { label: 'Deal Average', value: '€140K', highlight: false },
      { label: 'Retention Rate', value: '94%', highlight: false },
    ],
    outcomes: [
      'Secured €2.5M in annual contracts with major enterprises',
      'Built relationships with 18 Fortune 500 industrial companies',
      'Achieved 94% client retention rate',
      'Created scalable B2B partnership infrastructure',
    ],
  },
  {
    id: 6,
    title: 'eCommerce Global Fulfillment',
    category: 'tech',
    description: 'Built international logistics and fulfillment infrastructure for growing eCommerce platform',
    result: '12x customer growth',
    tags: ['eCommerce', 'Logistics', 'Scale'],
    image: '/ecommerce-warehouse-logistics.jpg',
    challenge: 'Fast-growing eCommerce platform struggling with fulfillment bottlenecks and unable to meet customer delivery expectations across regions. Limited international shipping capabilities.',
    solution: 'Built multi-regional warehouse infrastructure, implemented advanced fulfillment automation, created strategic shipping partnerships, and developed customer delivery optimization systems.',
    timeline: '15 months',
    metrics: [
      { label: 'Customer Growth', value: '12x', highlight: true },
      { label: 'Warehouses', value: '5 Locations', highlight: false },
      { label: 'Daily Fulfillment', value: '50K Orders', highlight: false },
      { label: 'Delivery Speed', value: '2-3 Days', highlight: false },
    ],
    outcomes: [
      'Increased customer base from 50K to 600K users',
      'Established 5 fulfillment centers across Europe',
      'Enabled same-day delivery in major cities',
      'Achieved 12x scaling of platform capacity',
    ],
  },
]
